// 移除 watch, CLEANUP_DAYS_THRESHOLD
import { onMessage, sendMessage } from 'webext-bridge/background'
import type { Tabs } from 'webextension-polyfill'
// src/background/main.ts
import { toRaw } from 'vue'
import {
  type Mark,
  marksByUrl,
  dataReady,
  tagsMetadata,
  keywordStats,
  type RemoveMarkPayload,
  type UpdateMarkNotePayload,
  GetMarkByIdPayload
} from '~/logic/storage'
import { extractKeywords, shouldPromoteToTag } from '~/logic/association'

// only on dev mode
if (import.meta.hot) {
  // @ts-expect-error for background HMR
  import('/@vite/client')
  // load latest content script
  import('./contentScriptHMR')
}

import { collectError } from '../logic/errorCollector'
window.addEventListener('error', (event) => collectError(event.error, 'background'))
window.addEventListener('unhandledrejection', (event) => collectError(event.reason, 'background'))

// remove or turn this off if you don't use side panel
const USE_SIDE_PANEL = true

// to toggle the sidepanel with the action button in chromium:
// @ts-expect-error missing types
if (USE_SIDE_PANEL && globalThis.browser?.sidePanel) {
  // @ts-expect-error missing types
  browser.sidePanel.setPanelBehavior({ openPanelOnActionClick: true }).catch((error: unknown) => console.error(error))
}

browser.runtime.onInstalled.addListener((): void => {
  // eslint-disable-next-line no-console
  console.log('Extension installed')
})

let previousTabId = 0

// communication example: send previous tab title from background page
// see shim.d.ts for type declaration
browser.tabs.onActivated.addListener(async ({ tabId }) => {
  if (!previousTabId) {
    previousTabId = tabId
    return
  }

  let tab: Tabs.Tab

  try {
    tab = await browser.tabs.get(previousTabId)
    previousTabId = tabId
  } catch {
    return
  }

  // eslint-disable-next-line no-console
  console.log('previous tab', tab)
  sendMessage('tab-prev', { title: tab.title }, { context: 'content-script', tabId })
})

onMessage('get-current-tab', async () => {
  try {
    const tab = await browser.tabs.get(previousTabId)
    return {
      title: tab?.title
    }
  } catch {
    return {
      title: undefined
    }
  }
})

/**
 * 核心：处理自动标签晋升逻辑（优化版：防抖处理 + 惰性关联）
 */
let autoTaggingTimer: any = null
async function debouncedAutoTagging(mark: Mark) {
  if (autoTaggingTimer) clearTimeout(autoTaggingTimer)
  autoTaggingTimer = setTimeout(() => {
    processAutoTagging(mark)
  }, 1000) // 1秒防抖
}

async function processAutoTagging(mark: Mark) {
  try {
    const domain = new URL(mark.url).hostname
    const keywords = extractKeywords(`${mark.title} ${mark.text}`)
    let needsPersistence = false

    for (const kw of keywords) {
      const key = kw.toLowerCase()
      if (!keywordStats.value[key]) {
        keywordStats.value[key] = { count: 0, domains: [] }
      }

      const stat = keywordStats.value[key]
      stat.count++
      if (!stat.domains.includes(domain)) {
        stat.domains.push(domain)
      }
      needsPersistence = true

      // 检查是否达到晋升阈值
      if (shouldPromoteToTag({ count: stat.count, domains: new Set(stat.domains) })) {
        let existingTag = Object.values(tagsMetadata.value).find(t => t.name.toLowerCase() === key)

        if (!existingTag) {
          const tagId = `auto-tag-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`
          existingTag = {
            id: tagId,
            name: kw,
            color: '#10B981',
            isAutoGenerated: true,
            createdAt: Date.now()
          }
          tagsMetadata.value[tagId] = existingTag
          
          // 仅在创建新标签时，执行一次全量历史标记关联（避免频繁扫描）
          Object.values(marksByUrl.value).forEach((pageMarks) => {
            pageMarks.forEach((m) => {
              if ((m.text.toLowerCase().includes(key) || m.title?.toLowerCase().includes(key))) {
                if (!m.tags) m.tags = []
                if (!m.tags.includes(existingTag!.id)) {
                  m.tags.push(existingTag!.id)
                }
              }
            })
          })
        }
        
        // 关联当前标记
        if (!mark.tags) mark.tags = []
        if (!mark.tags.includes(existingTag.id)) {
          mark.tags.push(existingTag.id)
        }
      }
    }

    if (needsPersistence) {
      keywordStats.value = { ...keywordStats.value }
      tagsMetadata.value = { ...tagsMetadata.value }
      marksByUrl.value = { ...marksByUrl.value }
    }
  } catch (e) {
    console.error('[background] Error in auto-tagging logic:', e)
  }
}

/**
 * 核心：清理关键词统计信息（优化版：重新计算确保准确性）
 */
function cleanupKeywordStats(mark: Mark) {
  const domain = new URL(mark.url).hostname
  const keywords = extractKeywords(`${mark.title} ${mark.text}`)
  let needsPersistence = false

  for (const kw of keywords) {
    const key = kw.toLowerCase()
    const stat = keywordStats.value[key]
    if (stat) {
      // 严谨做法：如果该域名下还有其他标记包含此词，则保留域名记录
      const domainStillHasKeyword = Object.values(marksByUrl.value)
        .filter((_, url) => new URL(url).hostname === domain)
        .flat()
        .some(m => m.id !== mark.id && (m.text.toLowerCase().includes(key) || m.title?.toLowerCase().includes(key)))
      
      stat.count = Math.max(0, stat.count - 1)
      if (!domainStillHasKeyword) {
        stat.domains = stat.domains.filter(d => d !== domain)
      }
      
      if (stat.count === 0 || stat.domains.length === 0) {
        delete keywordStats.value[key]
      }
      needsPersistence = true
    }
  }
  if (needsPersistence) {
    keywordStats.value = { ...keywordStats.value }
  }
}

onMessage('add-mark', async ({ data }) => {
  const { url } = data
  if (!marksByUrl.value[url]) marksByUrl.value[url] = []

  marksByUrl.value[url].push(data)
  marksByUrl.value = { ...marksByUrl.value } // 确保持久化

  // 异步防抖处理自动标签逻辑
  debouncedAutoTagging(data)
})

onMessage('remove-mark', async ({ data: markToRemove }) => {
  const { url, id } = markToRemove
  if (marksByUrl.value[url]) {
    const mark = marksByUrl.value[url].find(m => m.id === id)
    if (mark) {
      cleanupKeywordStats(mark)
      marksByUrl.value[url] = marksByUrl.value[url].filter((m) => m.id !== id)
      if (marksByUrl.value[url].length === 0) delete marksByUrl.value[url]
      marksByUrl.value = { ...marksByUrl.value }
    }
  }
})

onMessage('get-marks-for-url', async ({ data }) => {
  await dataReady
  const { url } = data
  // 返回空数组而不是 undefined，确保 Sidepanel 逻辑一致
  return (marksByUrl.value[url] || []).map(toRaw)
})

onMessage<RemoveMarkPayload>('remove-mark-by-id', async ({ data }) => {
  const { url, id } = data
  if (marksByUrl.value[url]) {
    const mark = marksByUrl.value[url].find(m => m.id === id)
    if (mark) {
      cleanupKeywordStats(mark)
      marksByUrl.value[url] = marksByUrl.value[url].filter((m) => m.id !== id)
      if (marksByUrl.value[url].length === 0) delete marksByUrl.value[url]
      marksByUrl.value = { ...marksByUrl.value }
    }
  }
})

onMessage<any>('update-mark-details', async ({ data }) => {
  const { url, id, ...updates } = data
  if (marksByUrl.value[url]) {
    const index = marksByUrl.value[url].findIndex((m) => m.id === id)
    if (index !== -1) {
      const markToUpdate = marksByUrl.value[url][index]
      Object.assign(markToUpdate, updates)
      marksByUrl.value = { ...marksByUrl.value }
      console.log(`[background] Mark ${id} updated successfully`)
    }
  }
})

onMessage<GetMarkByIdPayload>('get-mark-by-id', async ({ data }) => {
  const { url, id } = data
  if (marksByUrl.value[url]) {
    const markProxy = marksByUrl.value[url].find((m) => m.id === id)
    if (markProxy) return toRaw(markProxy)
  }
  return undefined
})

onMessage('get-storage-usage', async () => {
  const usage = await browser.storage.local.getBytesInUse()
  const rawQuota = (browser.storage.local as any).QUOTA_BYTES
  const quota = typeof rawQuota === 'number' ? rawQuota : 10 * 1024 * 1024
  return { usage, quota }
})

onMessage('cleanup-old-marks', async ({ data }) => {
  const { days } = data
  const threshold = Date.now() - days * 24 * 60 * 60 * 1000
  const allMarks = marksByUrl.value
  const keptMarks = Object.values(allMarks)
    .flat()
    .filter((mark: Mark) => mark.createdAt > threshold)

  marksByUrl.value = keptMarks.reduce((acc, mark) => {
    if (!acc[mark.url]) acc[mark.url] = []
    acc[mark.url].push(mark)
    return acc
  }, {} as Record<string, Mark[]>)
})

onMessage('cleanup-useless-marks', () => {
  const allMarks = marksByUrl.value
  const keptMarks = Object.values(allMarks)
    .flat()
    .filter((mark: Mark) => mark.note && mark.note.trim() !== '')

  marksByUrl.value = keptMarks.reduce((acc, mark) => {
    if (!acc[mark.url]) acc[mark.url] = []
    acc[mark.url].push(mark)
    return acc
  }, {} as Record<string, Mark[]>)
})

onMessage<{ tabId: number }>('open-sidepanel', async ({ data }) => {
  const { tabId } = data
  if (!tabId) return { success: false, error: 'Tab ID missing' }

  try {
    // @ts-expect-error missing types
    if (browser.sidePanel && typeof (browser.sidePanel as any).open === 'function') {
      // @ts-expect-error missing types
      await (browser.sidePanel as any).open({ tabId })
      return { success: true, browser: 'Chrome' }
    }
    return { success: false, error: 'Side panel/Sidebar API not found.' }
  } catch (e) {
    console.error('Failed to open side panel/sidebar:', e)
    return { success: false, error: `API call failed: ${(e as Error).message}` }
  }
})

onMessage<{ url: string }>('remove-marks-by-url', async ({ data }) => {
  const { url } = data
  if (marksByUrl.value[url]) {
    marksByUrl.value[url].forEach(cleanupKeywordStats)
    delete marksByUrl.value[url]
    marksByUrl.value = { ...marksByUrl.value }
  }
})

onMessage('get-all-marks', async () => {
  await dataReady
  const result: Record<string, Mark[]> = {}
  Object.entries(marksByUrl.value).forEach(([url, marks]) => {
    result[url] = marks.map(toRaw)
  })
  return result
})

onMessage('refresh-sidepanel-data', async () => {
  await browser.runtime.sendMessage({ type: 'refresh-sidepanel-data' }).catch(() => {})
})

onMessage('open-options-page', async () => {
  browser.runtime.openOptionsPage()
})

/**
 * 专门的消息处理器用于创建标签，解决 Content Script 直接修改存储的问题
 */
onMessage<{ name: string, color?: string }>('create-tag', async ({ data }) => {
  const { name, color = '#3B82F6' } = data
  const id = `tag-${Date.now()}`
  const newTag = { id, name, color, isAutoGenerated: false, createdAt: Date.now() }
  tagsMetadata.value = { ...tagsMetadata.value, [id]: newTag }
  return newTag
})

browser.runtime.onInstalled.addListener((details) => {
  if (details.reason === 'install') browser.runtime.openOptionsPage()
})
