// 移除 watch, CLEANUP_DAYS_THRESHOLD
import { onMessage, sendMessage } from 'webext-bridge/background'
import type { Tabs } from 'webextension-polyfill'
// src/background/main.ts
import { toRaw } from 'vue'
import {
  type Mark,
  marksByUrl,
  dataReady,
  tagsMetadata,
  keywordStats,
  type RemoveMarkPayload,
  type UpdateMarkNotePayload,
  GetMarkByIdPayload
} from '~/logic/storage'
import { extractKeywords, shouldPromoteToTag } from '~/logic/association'

// only on dev mode
if (import.meta.hot) {
  // @ts-expect-error for background HMR
  import('/@vite/client')
  // load latest content script
  import('./contentScriptHMR')
}

import { collectError } from '../logic/errorCollector'
window.addEventListener('error', (event) => collectError(event.error, 'background'))
window.addEventListener('unhandledrejection', (event) => collectError(event.reason, 'background'))

// remove or turn this off if you don't use side panel
const USE_SIDE_PANEL = true

// to toggle the sidepanel with the action button in chromium:
// @ts-expect-error missing types
if (USE_SIDE_PANEL && globalThis.browser?.sidePanel) {
  // @ts-expect-error missing types
  browser.sidePanel.setPanelBehavior({ openPanelOnActionClick: true }).catch((error: unknown) => console.error(error))
}

browser.runtime.onInstalled.addListener((): void => {
  // eslint-disable-next-line no-console
  console.log('Extension installed')
})

let previousTabId = 0

// communication example: send previous tab title from background page
// see shim.d.ts for type declaration
browser.tabs.onActivated.addListener(async ({ tabId }) => {
  if (!previousTabId) {
    previousTabId = tabId
    return
  }

  let tab: Tabs.Tab

  try {
    tab = await browser.tabs.get(previousTabId)
    previousTabId = tabId
  } catch {
    return
  }

  // eslint-disable-next-line no-console
  console.log('previous tab', tab)
  sendMessage('tab-prev', { title: tab.title }, { context: 'content-script', tabId })
})

onMessage('get-current-tab', async () => {
  try {
    const tab = await browser.tabs.get(previousTabId)
    return {
      title: tab?.title
    }
  } catch {
    return {
      title: undefined
    }
  }
})

/**
 * 核心：处理自动标签晋升与关联逻辑
 */
async function processAutoTagging(mark: Mark) {
  try {
    const domain = new URL(mark.url).hostname
    const keywords = extractKeywords(`${mark.title} ${mark.text}`)
    let needsPersistence = false

    for (const kw of keywords) {
      const key = kw.toLowerCase()
      if (!keywordStats.value[key]) {
        keywordStats.value[key] = { count: 0, domains: [] }
      }

      const stat = keywordStats.value[key]
      stat.count++
      if (!stat.domains.includes(domain)) {
        stat.domains.push(domain)
      }
      needsPersistence = true

      // 检查是否达到晋升阈值
      if (shouldPromoteToTag({ count: stat.count, domains: new Set(stat.domains) })) {
        // 检查是否已存在同名标签
        let existingTag = Object.values(tagsMetadata.value).find(t => t.name.toLowerCase() === key)

        if (!existingTag) {
          // 自动创建标签
          const tagId = `auto-tag-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`
          existingTag = {
            id: tagId,
            name: kw,
            color: '#10B981',
            isAutoGenerated: true,
            createdAt: Date.now()
          }
          tagsMetadata.value[tagId] = existingTag
          console.log(`[background] Auto-created tag: ${kw} (${tagId})`)
        }

        // 关联当前标记
        if (!mark.tags) mark.tags = []
        if (!mark.tags.includes(existingTag.id)) {
          mark.tags.push(existingTag.id)
        }

        // 扫描并关联历史标记
        Object.values(marksByUrl.value).forEach((pageMarks) => {
          pageMarks.forEach((m) => {
            if ((m.text.toLowerCase().includes(key) || m.title?.toLowerCase().includes(key))) {
              if (!m.tags) m.tags = []
              if (!m.tags.includes(existingTag!.id)) {
                m.tags.push(existingTag!.id)
              }
            }
          })
        })
      }
    }

    if (needsPersistence) {
      keywordStats.value = { ...keywordStats.value }
      tagsMetadata.value = { ...tagsMetadata.value }
      marksByUrl.value = { ...marksByUrl.value }
    }
  } catch (e) {
    console.error('[background] Error in auto-tagging logic:', e)
  }
}

/**
 * 核心：清理关键词统计信息
 */
function cleanupKeywordStats(mark: Mark) {
  const domain = new URL(mark.url).hostname
  const keywords = extractKeywords(`${mark.title} ${mark.text}`)
  let needsPersistence = false

  for (const kw of keywords) {
    const key = kw.toLowerCase()
    const stat = keywordStats.value[key]
    if (stat) {
      stat.count = Math.max(0, stat.count - 1)
      // 如果该关键词在当前域名下已无标记，则移除域名记录
      // 注意：这只是一个近似逻辑，因为一个域名下可能有多个标记包含同一个词
      // 严谨的做法需要扫描该域名下所有标记，但为了性能暂时采用递减
      if (stat.count === 0) {
        delete keywordStats.value[key]
      }
      needsPersistence = true
    }
  }
  if (needsPersistence) {
    keywordStats.value = { ...keywordStats.value }
  }
}

onMessage('add-mark', async ({ data }) => {
  console.log('Adding new mark:', data)
  const { url } = data
  if (!marksByUrl.value[url]) marksByUrl.value[url] = []

  marksByUrl.value[url].push(data)
  marksByUrl.value = { ...marksByUrl.value } // 确保持久化

  // 异步处理自动标签逻辑，不阻塞添加操作
  processAutoTagging(data)
})

onMessage('remove-mark', async ({ data: markToRemove }) => {
  const { url, id } = markToRemove
  if (marksByUrl.value[url]) {
    const mark = marksByUrl.value[url].find(m => m.id === id)
    if (mark) {
      cleanupKeywordStats(mark)
      marksByUrl.value[url] = marksByUrl.value[url].filter((m) => m.id !== id)
      if (marksByUrl.value[url].length === 0) delete marksByUrl.value[url]
      marksByUrl.value = { ...marksByUrl.value } // 确保持久化
    }
  }
})

onMessage('get-marks-for-url', async ({ data }) => {
  await dataReady
  const { url } = data
  const resultProxy = marksByUrl.value[url] || []
  return resultProxy.map(toRaw)
})

onMessage<RemoveMarkPayload>('remove-mark-by-id', async ({ data }) => {
  const { url, id } = data
  if (marksByUrl.value[url]) {
    const mark = marksByUrl.value[url].find(m => m.id === id)
    if (mark) {
      cleanupKeywordStats(mark)
      marksByUrl.value[url] = marksByUrl.value[url].filter((m) => m.id !== id)
      if (marksByUrl.value[url].length === 0) delete marksByUrl.value[url]
      marksByUrl.value = { ...marksByUrl.value }
    }
  }
})

onMessage<UpdateMarkNotePayload>('update-mark-note', async ({ data }) => {
  const { url, id, note } = data
  if (marksByUrl.value[url]) {
    const markToUpdate = marksByUrl.value[url].find((m) => m.id === id)
    if (markToUpdate) {
      markToUpdate.note = note
      marksByUrl.value = { ...marksByUrl.value }
    }
  }
})

onMessage<any>('update-mark-details', async ({ data }) => {
  const { url, id, ...updates } = data
  if (marksByUrl.value[url]) {
    const index = marksByUrl.value[url].findIndex((m) => m.id === id)
    if (index !== -1) {
      const markToUpdate = marksByUrl.value[url][index]
      Object.assign(markToUpdate, updates)
      marksByUrl.value = { ...marksByUrl.value }
      console.log(`[background] Mark ${id} updated successfully`)
    }
  }
})

onMessage<GetMarkByIdPayload>('get-mark-by-id', async ({ data }) => {
  const { url, id } = data
  if (marksByUrl.value[url]) {
    const markProxy = marksByUrl.value[url].find((m) => m.id === id)
    if (markProxy) return toRaw(markProxy)
  }
  return undefined
})

onMessage('get-storage-usage', async () => {
  const usage = await browser.storage.local.getBytesInUse()
  const rawQuota = (browser.storage.local as any).QUOTA_BYTES
  const quota = typeof rawQuota === 'number' ? rawQuota : 10 * 1024 * 1024
  return { usage, quota }
})

onMessage('cleanup-old-marks', async ({ data }) => {
  const { days } = data
  const threshold = Date.now() - days * 24 * 60 * 60 * 1000
  const allMarks = marksByUrl.value
  const keptMarks = Object.values(allMarks)
    .flat()
    .filter((mark: Mark) => mark.createdAt > threshold)

  marksByUrl.value = keptMarks.reduce((acc, mark) => {
    if (!acc[mark.url]) acc[mark.url] = []
    acc[mark.url].push(mark)
    return acc
  }, {} as Record<string, Mark[]>)
})

onMessage('cleanup-useless-marks', () => {
  const allMarks = marksByUrl.value
  const keptMarks = Object.values(allMarks)
    .flat()
    .filter((mark: Mark) => mark.note && mark.note.trim() !== '')

  marksByUrl.value = keptMarks.reduce((acc, mark) => {
    if (!acc[mark.url]) acc[mark.url] = []
    acc[mark.url].push(mark)
    return acc
  }, {} as Record<string, Mark[]>)
})

onMessage<{ tabId: number }>('open-sidepanel', async ({ data }) => {
  const { tabId } = data
  if (!tabId) return { success: false, error: 'Tab ID missing' }

  try {
    // @ts-expect-error missing types
    if (browser.sidePanel && typeof (browser.sidePanel as any).open === 'function') {
      // @ts-expect-error missing types
      await (browser.sidePanel as any).open({ tabId })
      return { success: true, browser: 'Chrome' }
    }
    return { success: false, error: 'Side panel/Sidebar API not found.' }
  } catch (e) {
    console.error('Failed to open side panel/sidebar:', e)
    return { success: false, error: `API call failed: ${(e as Error).message}` }
  }
})

onMessage<{ url: string }>('remove-marks-by-url', async ({ data }) => {
  const { url } = data
  if (marksByUrl.value[url]) {
    // 清理统计信息
    marksByUrl.value[url].forEach(cleanupKeywordStats)
    delete marksByUrl.value[url]
    marksByUrl.value = { ...marksByUrl.value }
  }
})

onMessage('refresh-sidepanel-data', async () => {
  await browser.runtime.sendMessage({ type: 'refresh-sidepanel-data' }).catch(() => {})
})

onMessage('open-options-page', async () => {
  browser.runtime.openOptionsPage()
})

browser.runtime.onInstalled.addListener((details) => {
  if (details.reason === 'install') browser.runtime.openOptionsPage()
})
