import { useWebExtensionStorage } from '~/composables/useWebExtensionStorage'

export const { data: marksByUrl, dataReady } = useWebExtensionStorage<Record<string, Mark[]>>(
  'marks-by-url-storage',
  {}
)

export interface Tag {
  id: string
  name: string
  color: string
  isAutoGenerated: boolean
  createdAt: number
}

export const { data: tagsMetadata, dataReady: tagsReady } = useWebExtensionStorage<Record<string, Tag>>(
  'webmarker-tags-metadata',
  {}
)

export interface SyncConfig {
  enabled: boolean
  token: string
  gistId: string
  lastSyncTime: number
  autoSync: boolean
}

export const { data: syncConfig, dataReady: syncReady } = useWebExtensionStorage<SyncConfig>(
  'webmarker-sync-config',
  { enabled: false, token: '', gistId: '', lastSyncTime: 0, autoSync: true }
)

export interface Mark {
  id: string // 唯一ID
  url: string // 标记所在的页面URL
  text: string // 高亮的文本内容
  note: string // 备注
  color: string // 高亮颜色
  html?: string // 新增：高亮内容的 HTML 格式
  rangySerialized: string // Rangy 序列化后的选区字符串
  shadowHostSelector?: string // 新增：如果高亮在 Shadow DOM 中，则存储其宿主元素的选择器
  createdAt: number // 创建时间戳
  title?: string // 网页 tab 名称
  domIndex?: number // 新增：用于物理位置排序
  tags?: string[] // 新增：关联的标签 ID 列表
  contextTitle?: string
  contextLevel?: number
  contextSelector?: string
  contextOrder?: number
  surroundingSnippet?: string
  deletedAt?: number // 新增：删除时间戳，用于同步删除
}

export interface RemoveMarkPayload {
  url: string
  id: Mark['id']
  [key: string]: any
}

export interface UpdateMarkNotePayload {
  url: string
  id: Mark['id']
  note: string
  [key: string]: any
}

export interface GetMarkByIdPayload {
  url: string
  id: Mark['id']
  [key: string]: any
}
